/**
 * Pure, platform-agnostic dashboard derivations shared by web and mobile.
 * No React / DOM / canvas — safe to import from React Native.
 */
import type { Routine } from "@beyou/types/routine/routine";
import type { check } from "@beyou/types/routine/routineSection";

export type GreetingKey = "GoodMorning" | "GoodAfternoon" | "GoodEvening" | "GoodNight";

/** Maps an hour (0-23) to the i18n greeting key. */
export function getGreetingKey(hour: number): GreetingKey {
  if (hour >= 5 && hour < 12) return "GoodMorning";
  if (hour >= 12 && hour < 17) return "GoodAfternoon";
  if (hour >= 17 && hour < 21) return "GoodEvening";
  return "GoodNight";
}

/**
 * Percentage (0-100) of progress within the current level's XP window.
 * Mirrors the web levelProgress widget: clamped, rounded, guards a zero/negative
 * window. `xp` is the total XP; `actualLevelXp`/`nextLevelXp` bound the level.
 */
export function calculateLevelProgress(
  xp: number,
  actualLevelXp: number,
  nextLevelXp: number,
): number {
  const xpWindow = nextLevelXp - actualLevelXp;
  if (xpWindow <= 0) return 0;
  return Math.min(100, Math.max(0, Math.round(((xp - actualLevelXp) / xpWindow) * 100)));
}

/**
 * Count today's checked items vs total across a routine. An item counts as
 * "checked" only when its check for `today` has `checked === true` (skipped does
 * NOT count) — mirrors the web isItemChecked / dashboard sync. `today` is
 * YYYY-MM-DD.
 */
export function calculateDailyProgress(
  routine: Routine | null | undefined,
  today: string,
): { checked: number; total: number } {
  let checked = 0;
  let total = 0;
  if (!routine) return { checked, total };
  for (const section of routine.routineSections ?? []) {
    const groupChecks: (check[] | undefined)[] = [
      ...(section.habitGroup ?? []).map((g) => g.habitGroupChecks),
      ...(section.taskGroup ?? []).map((g) => g.taskGroupChecks),
    ];
    for (const checks of groupChecks) {
      total++;
      const c = (checks ?? []).find((x) => x?.checkDate === today);
      if (c?.checked === true) checked++;
    }
  }
  return { checked, total };
}

/** Sum of XP generated by today's checked items across a routine. */
export function calculateRoutineXpToday(routine: Routine | null | undefined, today: string): number {
  if (!routine) return 0;
  let xp = 0;
  for (const section of routine.routineSections ?? []) {
    const groupChecks: (check[] | undefined)[] = [
      ...(section.habitGroup ?? []).map((g) => g.habitGroupChecks),
      ...(section.taskGroup ?? []).map((g) => g.taskGroupChecks),
    ];
    for (const checks of groupChecks) {
      for (const c of checks ?? []) {
        if (c?.checkDate === today && c?.checked) xp += c?.xpGenerated ?? 0;
      }
    }
  }
  return xp;
}
