/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getProfile"];
        put: operations["editUser"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/task": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTasks"];
        put: operations["editTask"];
        post: operations["createTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAllSchedules"];
        put: operations["updateSchedule"];
        post: operations["createSchedule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/routine/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getDiaryRoutineById"];
        put: operations["updateDiaryRoutine"];
        post?: never;
        delete: operations["deleteDiaryRoutine"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/habit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getHabits"];
        put: operations["editHabit"];
        post: operations["createHabit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/goal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getGoals"];
        put: operations["editGoal"];
        post: operations["createGoal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/goal/increase": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["increaseCurrentValue"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/goal/decrease": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["decreaseCurrentValue"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/goal/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["setAsComplete"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/category": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCategories"];
        put: operations["editCategory"];
        post: operations["createCategory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/routine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAllDiaryRoutines"];
        put?: never;
        post: operations["createDiaryRoutine"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/routine/snapshot/skip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["skipSnapshotItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/routine/snapshot/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["checkSnapshotItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/routine/skip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["skipItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/routine/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["checkItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/docs/admin/import/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["importProjects"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/docs/admin/import/blog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["importBlog"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/docs/admin/import/architecture": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["importArchitecture"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/docs/admin/import/api": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["importApi"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["resetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["doRegister"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refreshAccess"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["doLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["forgotPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/routine/materialize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["materialize"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/routine/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["generate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/routine/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["confirm"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["exportUserData"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/routine/{routineId}/snapshots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSnapshotDatesForMonth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/routine/{routineId}/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSnapshot"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/routine/today": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTodayRoutineScheduled"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/docs/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/docs/projects/topics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTopics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/docs/projects/topics/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTopic"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/docs/blog/topics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTopics_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/docs/blog/topics/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTopic_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/docs/architecture/topics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTopics_2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/docs/architecture/topics/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTopic_2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/docs/api/controllers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getControllers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/docs/api/controllers/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getController"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["verifyAuthentication"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["verifyEmail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/reset-password/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["validateResetPasswordToken"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["googleAuth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/task/{taskId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteTask"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schedule/{scheduleId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteSchedule"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/habit/{habitId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteHabit"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/goal/{goalId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteGoal"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/category/{categoryId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteCategory"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        UserEditDTO: {
            name?: string;
            photo?: string;
            phrase?: string;
            phrase_author?: string;
            widgetsId?: string[];
            theme?: string;
            /** @enum {string} */
            constanceConfiguration?: "ANY" | "COMPLETE";
            language?: string;
            isTutorialCompleted?: boolean;
            timezone?: string;
            /** @enum {string} */
            xpDecayStrategy?: "GRADUAL" | "FLAT" | "TIME_WINDOW";
        };
        UserResponseDTO: {
            name?: string;
            email?: string;
            phrase?: string;
            phrase_author?: string;
            /** Format: int32 */
            constance?: number;
            photo?: string;
            isGoogleAccount?: boolean;
            widgetsId?: string[];
            themeInUse?: string;
            /** Format: double */
            xp?: number;
            /** Format: double */
            actualLevelXp?: number;
            /** Format: double */
            nextLevelXp?: number;
            /** Format: int32 */
            level?: number;
            /** @enum {string} */
            constanceConfiguration?: "ANY" | "COMPLETE";
            constanceIncreaseToday?: boolean;
            /** Format: int32 */
            maxConstance?: number;
            isTutorialCompleted?: boolean;
            languageInUse?: string;
            timezone?: string;
            /** @enum {string} */
            xpDecayStrategy?: "GRADUAL" | "FLAT" | "TIME_WINDOW";
        };
        EditTaskRequestDTO: {
            /** Format: uuid */
            taskId?: string;
            name?: string;
            description?: string;
            iconId?: string;
            /** Format: int32 */
            importance: number;
            /** Format: int32 */
            difficulty: number;
            categoriesId?: string[];
            oneTimeTask?: boolean;
        };
        UpdateScheduleDTO: {
            /** Format: uuid */
            scheduleId?: string;
            days?: ("Monday" | "Tuesday" | "Wednesday" | "Thursday" | "Friday" | "Saturday" | "Sunday")[];
            /** Format: uuid */
            routineId?: string;
        };
        Schedule: {
            /** Format: uuid */
            id?: string;
            days?: ("Monday" | "Tuesday" | "Wednesday" | "Thursday" | "Friday" | "Saturday" | "Sunday")[];
        };
        DiaryRoutineRequestDTO: {
            name?: string;
            iconId?: string;
            routineSections?: components["schemas"]["RoutineSectionRequestDTO"][];
        };
        HabitGroupCheck: {
            /** Format: uuid */
            id?: string;
            /** Format: date */
            checkDate?: string;
            checkTime?: string;
            checked?: boolean;
            skipped?: boolean;
            /** Format: double */
            xpGenerated?: number;
        };
        HabitGroupDTO: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            habitId?: string;
            startTime?: string;
            endTime?: string;
            habitGroupCheck?: components["schemas"]["HabitGroupCheck"][];
        };
        RoutineSectionRequestDTO: {
            /** Format: uuid */
            id?: string;
            name?: string;
            iconId?: string;
            startTime?: string;
            endTime?: string;
            taskGroup?: components["schemas"]["TaskGroupDTO"][];
            habitGroup?: components["schemas"]["HabitGroupDTO"][];
            favorite?: boolean;
        };
        TaskGroupCheck: {
            /** Format: uuid */
            id?: string;
            /** Format: date */
            checkDate?: string;
            checkTime?: string;
            checked?: boolean;
            skipped?: boolean;
            /** Format: double */
            xpGenerated?: number;
        };
        TaskGroupDTO: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            taskId?: string;
            startTime?: string;
            endTime?: string;
            taskGroupCheck?: components["schemas"]["TaskGroupCheck"][];
        };
        DiaryRoutineResponseDTO: {
            /** Format: uuid */
            id?: string;
            name?: string;
            iconId?: string;
            routineSections?: components["schemas"]["RoutineSectionResponseDTO"][];
            schedule?: components["schemas"]["ScheduleResponseDTO"];
            /** Format: double */
            xp?: number;
            /** Format: double */
            actualLevelXp?: number;
            /** Format: double */
            nextLevelXp?: number;
            /** Format: int32 */
            level?: number;
        };
        HabitGroupResponseDTO: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            habitId?: string;
            startTime?: string;
            endTime?: string;
            habitGroupChecks?: components["schemas"]["HabitGroupCheck"][];
        };
        RoutineSectionResponseDTO: {
            /** Format: uuid */
            id?: string;
            name?: string;
            iconId?: string;
            startTime?: string;
            endTime?: string;
            taskGroup?: components["schemas"]["TaskGroupResponseDTO"][];
            habitGroup?: components["schemas"]["HabitGroupResponseDTO"][];
            favorite?: boolean;
        };
        ScheduleResponseDTO: {
            /** Format: uuid */
            id?: string;
            days?: ("Monday" | "Tuesday" | "Wednesday" | "Thursday" | "Friday" | "Saturday" | "Sunday")[];
        };
        TaskGroupResponseDTO: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            taskId?: string;
            startTime?: string;
            endTime?: string;
            taskGroupChecks?: components["schemas"]["TaskGroupCheck"][];
        };
        EditHabitDTO: {
            /** Format: uuid */
            habitId?: string;
            name?: string;
            description?: string;
            motivationalPhrase?: string;
            iconId?: string;
            /** Format: int32 */
            importance: number;
            /** Format: int32 */
            dificulty: number;
            categoriesId?: string[];
        };
        EditGoalRequestDTO: {
            /** Format: uuid */
            goalId: string;
            name: string;
            iconId?: string;
            description?: string;
            /** Format: double */
            targetValue: number;
            unit: string;
            /** Format: double */
            currentValue: number;
            complete: boolean;
            categoriesId: string[];
            motivation?: string;
            /** Format: date */
            startDate: string;
            /** Format: date */
            endDate: string;
            /** @enum {string} */
            status: "NOT_STARTED" | "IN_PROGRESS" | "COMPLETED";
            /** @enum {string} */
            term: "SHORT_TERM" | "MEDIUM_TERM" | "LONG_TERM";
        };
        CategoryMiniDTO: {
            name?: string;
            iconId?: string;
        };
        GoalResponseDTO: {
            /** Format: uuid */
            id?: string;
            name?: string;
            iconId?: string;
            description?: string;
            /** Format: double */
            targetValue?: number;
            unit?: string;
            /** Format: double */
            currentValue?: number;
            complete?: boolean;
            categories?: {
                [key: string]: components["schemas"]["CategoryMiniDTO"];
            };
            motivation?: string;
            /** Format: date */
            startDate?: string;
            /** Format: date */
            endDate?: string;
            /** Format: double */
            xpReward?: number;
            /** @enum {string} */
            status?: "NOT_STARTED" | "IN_PROGRESS" | "COMPLETED";
            /** @enum {string} */
            term?: "SHORT_TERM" | "MEDIUM_TERM" | "LONG_TERM";
            /** Format: date */
            completeDate?: string;
        };
        BaseCheck: {
            /** Format: uuid */
            id?: string;
            /** Format: date */
            checkDate?: string;
            checkTime?: string;
            checked?: boolean;
            skipped?: boolean;
            /** Format: double */
            xpGenerated?: number;
        };
        RefreshItemCheckedDTO: {
            /** Format: uuid */
            groupItemId?: string;
            check?: components["schemas"]["BaseCheck"];
        };
        RefreshObjectDTO: {
            /** Format: uuid */
            id?: string;
            /** Format: double */
            xp?: number;
            /** Format: int32 */
            level?: number;
            /** Format: double */
            actualLevelXp?: number;
            /** Format: double */
            nextLevelXp?: number;
        };
        RefreshUiDTO: {
            refreshUser?: components["schemas"]["RefreshUserDTO"];
            refreshCategories?: components["schemas"]["RefreshObjectDTO"][];
            refreshHabit?: components["schemas"]["RefreshObjectDTO"];
            refreshItemChecked?: components["schemas"]["RefreshItemCheckedDTO"];
        };
        RefreshUserDTO: {
            /** Format: int32 */
            currentConstance?: number;
            alreadyIncreaseConstanceToday?: boolean;
            /** Format: int32 */
            maxConstance?: number;
            /** Format: double */
            xp?: number;
            /** Format: int32 */
            level?: number;
            /** Format: double */
            actualLevelXp?: number;
            /** Format: double */
            nextLevelXp?: number;
        };
        CategoryEditRequestDTO: {
            categoryId: string;
            name: string;
            icon: string;
            description?: string;
        };
        CreateTaskRequestDTO: {
            name: string;
            description?: string;
            iconId: string;
            /** Format: int32 */
            importance: number;
            /** Format: int32 */
            difficulty: number;
            categoriesId?: string[];
            oneTimeTask?: boolean;
        };
        CreateScheduleDTO: {
            days: ("Monday" | "Tuesday" | "Wednesday" | "Thursday" | "Friday" | "Saturday" | "Sunday")[];
            /** Format: uuid */
            routineId: string;
        };
        SnapshotCheckRequestDTO: {
            /** Format: uuid */
            snapshotId: string;
            /** Format: uuid */
            snapshotCheckId: string;
        };
        HabitGroupRequestDTO: {
            /** Format: uuid */
            habitGroupId?: string;
            startTime?: string;
        };
        SkipGroupRequestDTO: {
            /** Format: uuid */
            routineId?: string;
            taskGroupDTO?: components["schemas"]["TaskGroupRequestDTO"];
            habitGroupDTO?: components["schemas"]["HabitGroupRequestDTO"];
            /** Format: date */
            date?: string;
            skip?: boolean;
        };
        TaskGroupRequestDTO: {
            /** Format: uuid */
            taskGroupId?: string;
            startTime?: string;
        };
        CheckGroupRequestDTO: {
            /** Format: uuid */
            routineId?: string;
            taskGroupDTO?: components["schemas"]["TaskGroupRequestDTO"];
            habitGroupDTO?: components["schemas"]["HabitGroupRequestDTO"];
            /** Format: date */
            date?: string;
        };
        CreateHabitDTO: {
            name: string;
            description?: string;
            motivationalPhrase?: string;
            iconId: string;
            /** Format: int32 */
            importance: number;
            /** Format: int32 */
            dificulty: number;
            categoriesId?: string[];
            /** @enum {string} */
            experience: "BEGINNER" | "INTERMEDIARY" | "ADVANCED";
        };
        CreateGoalRequestDTO: {
            name: string;
            description?: string;
            iconId?: string;
            /** Format: double */
            targetValue: number;
            unit: string;
            /** Format: double */
            currentValue: number;
            categoriesId: string[];
            motivation?: string;
            /** Format: date */
            startDate: string;
            /** Format: date */
            endDate: string;
            /** @enum {string} */
            status: "NOT_STARTED" | "IN_PROGRESS" | "COMPLETED";
            /** @enum {string} */
            term: "SHORT_TERM" | "MEDIUM_TERM" | "LONG_TERM";
        };
        ProjectDocsImportRequestDTO: {
            repoOwner?: string;
            repoName?: string;
            branch?: string;
            path?: string;
            token?: string;
        };
        BlogDocsImportRequestDTO: {
            repoOwner?: string;
            repoName?: string;
            branch?: string;
            path?: string;
            token?: string;
        };
        ArchitectureDocsImportRequestDTO: {
            repoOwner?: string;
            repoName?: string;
            branch?: string;
            path?: string;
            token?: string;
        };
        ApiDocsImportRequestDTO: {
            repoOwner?: string;
            repoName?: string;
            branch?: string;
            path?: string;
            token?: string;
        };
        CategoryRequestDTO: {
            name: string;
            icon: string;
            description?: string;
            /** @enum {string} */
            experience: "BEGINNER" | "INTERMEDIARY" | "ADVANCED";
        };
        ResetPasswordRequestDTO: {
            token: string;
            password: string;
        };
        UserRegisterDTO: {
            name: string;
            /** Format: email */
            email: string;
            password: string;
        };
        UserLoginDTO: {
            email: string;
            password: string;
        };
        ForgotPasswordRequestDTO: {
            /** Format: email */
            email: string;
        };
        DraftHabitItemDTO: {
            /** Format: uuid */
            existingHabitId?: string;
            newHabit?: components["schemas"]["DraftNewHabitDTO"];
            startTime?: string;
            endTime?: string;
        };
        DraftNewCategoryDTO: {
            tempKey: string;
            name: string;
            icon?: string;
            description?: string;
        };
        DraftNewHabitDTO: {
            name: string;
            description?: string;
            motivationalPhrase?: string;
            iconId?: string;
            /** Format: int32 */
            importance?: number;
            /** Format: int32 */
            dificulty?: number;
            categoryRefs?: string[];
        };
        DraftNewTaskDTO: {
            name: string;
            description?: string;
            iconId?: string;
            /** Format: int32 */
            importance?: number;
            /** Format: int32 */
            difficulty?: number;
            categoryRefs?: string[];
            oneTimeTask?: boolean;
        };
        DraftSectionDTO: {
            name: string;
            iconId?: string;
            startTime: string;
            endTime?: string;
            habits?: components["schemas"]["DraftHabitItemDTO"][];
            tasks?: components["schemas"]["DraftTaskItemDTO"][];
        };
        DraftTaskItemDTO: {
            /** Format: uuid */
            existingTaskId?: string;
            newTask?: components["schemas"]["DraftNewTaskDTO"];
            startTime?: string;
            endTime?: string;
        };
        RoutineDraftDTO: {
            name: string;
            iconId?: string;
            newCategories?: components["schemas"]["DraftNewCategoryDTO"][];
            sections: components["schemas"]["DraftSectionDTO"][];
            scheduleDays?: ("Monday" | "Tuesday" | "Wednesday" | "Thursday" | "Friday" | "Saturday" | "Sunday")[];
        };
        HabitGroupRefDTO: {
            /** Format: uuid */
            habitId?: string;
            startTime?: string;
            endTime?: string;
        };
        MaterializeRoutineResponseDTO: {
            name?: string;
            iconId?: string;
            scheduleDays?: ("Monday" | "Tuesday" | "Wednesday" | "Thursday" | "Friday" | "Saturday" | "Sunday")[];
            sections?: components["schemas"]["SectionDTO"][];
            newCategoryIds?: string[];
            newHabitIds?: string[];
            newTaskIds?: string[];
        };
        SectionDTO: {
            name?: string;
            iconId?: string;
            startTime?: string;
            endTime?: string;
            habitGroup?: components["schemas"]["HabitGroupRefDTO"][];
            taskGroup?: components["schemas"]["TaskGroupRefDTO"][];
        };
        TaskGroupRefDTO: {
            /** Format: uuid */
            taskId?: string;
            startTime?: string;
            endTime?: string;
        };
        GenerateRoutineRequestDTO: {
            description: string;
            previousDraft?: components["schemas"]["RoutineDraftDTO"];
            feedback?: string;
            language?: string;
        };
        GenerateRoutineResponseDTO: {
            draft?: components["schemas"]["RoutineDraftDTO"];
        };
        TaskResponseDTO: {
            /** Format: uuid */
            id?: string;
            name?: string;
            description?: string;
            iconId?: string;
            /** Format: int32 */
            importance?: number;
            /** Format: int32 */
            difficulty?: number;
            categories?: {
                [key: string]: components["schemas"]["CategoryMiniDTO"];
            };
            oneTimeTask?: boolean;
            /** Format: date */
            markedToDelete?: string;
            /** Format: date */
            createdAt?: string;
            /** Format: date */
            updatedAt?: string;
        };
        SnapshotMonthResponseDTO: {
            dates?: string[];
        };
        SnapshotCheckResponseDTO: {
            /** Format: uuid */
            id?: string;
            /** @enum {string} */
            itemType?: "HABIT" | "TASK";
            itemName?: string;
            itemIconId?: string;
            sectionName?: string;
            /** Format: uuid */
            originalGroupId?: string;
            /** Format: int32 */
            difficulty?: number;
            /** Format: int32 */
            importance?: number;
            checked?: boolean;
            skipped?: boolean;
            checkTime?: string;
            /** Format: double */
            xpGenerated?: number;
        };
        SnapshotResponseDTO: {
            /** Format: uuid */
            id?: string;
            /** Format: date */
            snapshotDate?: string;
            routineName?: string;
            routineIconId?: string;
            completed?: boolean;
            structure?: string;
            checks?: components["schemas"]["SnapshotCheckResponseDTO"][];
        };
        Category: {
            /** Format: uuid */
            id?: string;
            name: string;
            description?: string;
            iconId?: string;
            xpProgress?: components["schemas"]["XpProgress"];
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        HabitResponseDTO: {
            /** Format: uuid */
            id?: string;
            name?: string;
            description?: string;
            motivationalPhrase?: string;
            iconId?: string;
            /** Format: int32 */
            importance?: number;
            /** Format: int32 */
            dificulty?: number;
            categories?: components["schemas"]["Category"][];
            /** Format: double */
            xp?: number;
            /** Format: double */
            actualLevelXp?: number;
            /** Format: double */
            nextLevelXp?: number;
            /** Format: int32 */
            level?: number;
            /** Format: int32 */
            constance?: number;
            /** Format: date */
            createdAt?: string;
            /** Format: date */
            updatedAt?: string;
            routines?: {
                [key: string]: string;
            };
        };
        XpProgress: {
            /** Format: double */
            xp?: number;
            /** Format: int32 */
            level?: number;
            /** Format: double */
            actualLevelXp?: number;
            /** Format: double */
            nextLevelXp?: number;
        };
        SearchHighlightDTO: {
            title?: string[];
            summary?: string[];
        };
        SearchResultDTO: {
            type?: string;
            key?: string;
            title?: string;
            summary?: string;
            /** Format: date-time */
            updatedAt?: string;
            /** Format: double */
            score?: number;
            highlight?: components["schemas"]["SearchHighlightDTO"];
        };
        ProjectTopicListItemDTO: {
            key?: string;
            title?: string;
            summary?: string;
            /** Format: int32 */
            orderIndex?: number;
            /** Format: date-time */
            updatedAt?: string;
            status?: string;
            tags?: string;
        };
        ProjectTopicDetailDTO: {
            key?: string;
            title?: string;
            docMarkdown?: string;
            diagramMermaid?: string;
            designTopicKey?: string;
            architectureTopicKey?: string;
            repositoryUrl?: string;
            tags?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        BlogTopicListItemDTO: {
            key?: string;
            title?: string;
            summary?: string;
            category?: string;
            tags?: string;
            featured?: boolean;
            /** Format: date-time */
            publishedAt?: string;
            coverColor?: string;
            coverEmoji?: string;
            author?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        BlogTopicDetailDTO: {
            key?: string;
            title?: string;
            docMarkdown?: string;
            category?: string;
            tags?: string;
            featured?: boolean;
            /** Format: date-time */
            publishedAt?: string;
            coverColor?: string;
            coverEmoji?: string;
            author?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        ArchitectureTopicListItemDTO: {
            key?: string;
            title?: string;
            summary?: string;
            /** Format: int32 */
            orderIndex?: number;
            /** Format: date-time */
            updatedAt?: string;
            status?: string;
            tags?: string;
            projectKey?: string;
        };
        ArchitectureTopicDetailDTO: {
            key?: string;
            title?: string;
            diagramMermaid?: string;
            docMarkdown?: string;
            /** Format: date-time */
            updatedAt?: string;
            status?: string;
            tags?: string;
            projectKey?: string;
        };
        ApiControllerListItemDTO: {
            key?: string;
            title?: string;
            summary?: string;
            /** Format: int32 */
            orderIndex?: number;
            /** Format: date-time */
            updatedAt?: string;
        };
        ApiControllerDetailDTO: {
            key?: string;
            title?: string;
            summary?: string;
            apiCatalog?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        CategoryResponseDTO: {
            /** Format: uuid */
            id?: string;
            name?: string;
            description?: string;
            iconId?: string;
            habits?: {
                [key: string]: string;
            };
            tasks?: {
                [key: string]: string;
            };
            goals?: {
                [key: string]: string;
            };
            /** Format: double */
            xp?: number;
            /** Format: double */
            nextLevelXp?: number;
            /** Format: double */
            actualLevelXp?: number;
            /** Format: int32 */
            level?: number;
            /** Format: date-time */
            createdAt?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponseDTO"];
                };
            };
        };
    };
    editUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserEditDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponseDTO"];
                };
            };
        };
    };
    getTasks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TaskResponseDTO"][];
                };
            };
        };
    };
    editTask: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EditTaskRequestDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    createTask: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTaskRequestDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    getAllSchedules: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ScheduleResponseDTO"][];
                };
            };
        };
    };
    updateSchedule: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateScheduleDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Schedule"];
                };
            };
        };
    };
    createSchedule: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateScheduleDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Schedule"];
                };
            };
        };
    };
    getDiaryRoutineById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DiaryRoutineResponseDTO"];
                };
            };
        };
    };
    updateDiaryRoutine: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DiaryRoutineRequestDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DiaryRoutineResponseDTO"];
                };
            };
        };
    };
    deleteDiaryRoutine: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getHabits: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HabitResponseDTO"][];
                };
            };
        };
    };
    editHabit: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EditHabitDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    createHabit: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateHabitDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    getGoals: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GoalResponseDTO"][];
                };
            };
        };
    };
    editGoal: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EditGoalRequestDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    createGoal: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateGoalRequestDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    increaseCurrentValue: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": string;
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GoalResponseDTO"];
                };
            };
        };
    };
    decreaseCurrentValue: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": string;
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GoalResponseDTO"];
                };
            };
        };
    };
    setAsComplete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": string;
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RefreshUiDTO"];
                };
            };
        };
    };
    getCategories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CategoryResponseDTO"][];
                };
            };
        };
    };
    editCategory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryEditRequestDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    createCategory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryRequestDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    getAllDiaryRoutines: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DiaryRoutineResponseDTO"][];
                };
            };
        };
    };
    createDiaryRoutine: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DiaryRoutineRequestDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DiaryRoutineResponseDTO"];
                };
            };
        };
    };
    skipSnapshotItem: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SnapshotCheckRequestDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RefreshUiDTO"];
                };
            };
        };
    };
    checkSnapshotItem: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SnapshotCheckRequestDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RefreshUiDTO"];
                };
            };
        };
    };
    skipItem: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SkipGroupRequestDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RefreshUiDTO"];
                };
            };
        };
    };
    checkItem: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckGroupRequestDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RefreshUiDTO"];
                };
            };
        };
    };
    importProjects: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ProjectDocsImportRequestDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    importBlog: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["BlogDocsImportRequestDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    importArchitecture: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ArchitectureDocsImportRequestDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    importApi: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ApiDocsImportRequestDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    resetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordRequestDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    doRegister: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserRegisterDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    refreshAccess: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    doLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserLoginDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    forgotPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordRequestDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    materialize: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoutineDraftDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MaterializeRoutineResponseDTO"];
                };
            };
        };
    };
    generate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateRoutineRequestDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GenerateRoutineResponseDTO"];
                };
            };
        };
    };
    confirm: {
        parameters: {
            query?: {
                routineId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoutineDraftDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DiaryRoutineResponseDTO"];
                };
            };
        };
    };
    exportUserData: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    getSnapshotDatesForMonth: {
        parameters: {
            query: {
                month: string;
            };
            header?: never;
            path: {
                routineId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SnapshotMonthResponseDTO"];
                };
            };
        };
    };
    getSnapshot: {
        parameters: {
            query: {
                date: string;
            };
            header?: never;
            path: {
                routineId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SnapshotResponseDTO"];
                };
            };
        };
    };
    getTodayRoutineScheduled: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DiaryRoutineResponseDTO"];
                };
            };
        };
    };
    search: {
        parameters: {
            query: {
                q: string;
                locale?: string;
                category?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SearchResultDTO"][];
                };
            };
        };
    };
    getTopics: {
        parameters: {
            query?: {
                locale?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProjectTopicListItemDTO"][];
                };
            };
        };
    };
    getTopic: {
        parameters: {
            query?: {
                locale?: string;
            };
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProjectTopicDetailDTO"];
                };
            };
        };
    };
    getTopics_1: {
        parameters: {
            query?: {
                locale?: string;
                category?: string;
                tag?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BlogTopicListItemDTO"][];
                };
            };
        };
    };
    getTopic_1: {
        parameters: {
            query?: {
                locale?: string;
            };
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BlogTopicDetailDTO"];
                };
            };
        };
    };
    getTopics_2: {
        parameters: {
            query?: {
                locale?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ArchitectureTopicListItemDTO"][];
                };
            };
        };
    };
    getTopic_2: {
        parameters: {
            query?: {
                locale?: string;
            };
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ArchitectureTopicDetailDTO"];
                };
            };
        };
    };
    getControllers: {
        parameters: {
            query?: {
                locale?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiControllerListItemDTO"][];
                };
            };
        };
    };
    getController: {
        parameters: {
            query?: {
                locale?: string;
            };
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiControllerDetailDTO"];
                };
            };
        };
    };
    verifyAuthentication: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    verifyEmail: {
        parameters: {
            query: {
                token: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    validateResetPasswordToken: {
        parameters: {
            query: {
                token: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    googleAuth: {
        parameters: {
            query: {
                code: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    deleteTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taskId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    deleteSchedule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scheduleId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteHabit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                habitId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    deleteGoal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                goalId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    deleteCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                categoryId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
