import extraIconNodes from './data/extraIconNodes.json';
import type { LucideIconNode } from './types';

// TypeScript widens the imported JSON's `[tag, attrs]` pairs to plain arrays, which
// no longer match the tuple type, so the cast goes through `unknown`. The shape is
// guaranteed by the generator (it copies lucide's own `__iconNode`) and asserted in
// the test suite.
const nodes = extraIconNodes as unknown as Record<string, LucideIconNode>;

/**
 * Raw SVG path data for lucide names that `lucide-react-native` does not export.
 *
 * Lucide 1.x dropped the brand marks (github, figma, slack, youtube…) for trademark
 * reasons, but web is on lucide-react 0.474 which still ships them — so they are in
 * the picker and users pick them. Rather than remove icons people chose, mobile draws
 * them from this committed path data through lucide's own generic `Icon` component,
 * which takes exactly this shape as `iconNode`.
 *
 * Generated by `scripts/generate-data.mjs` off the two installed lucide packages, so
 * bumping either one re-derives the list instead of leaving a stale hand-written map.
 */
export const getExtraIconNode = (lucideName: string): LucideIconNode | undefined =>
  nodes[lucideName];

/** Every lucide name that needs the path-data path on mobile. */
export const getExtraIconNames = (): string[] => Object.keys(nodes);
